yatube/about/urls.py
# файл about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'), 
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'), 
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    # Все адреса с префиксом auth/ 
    # будут перенаправлены в модуль django.contrib.auth
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),

]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=300)
    slug = models.SlugField(max_length=300, unique=True)
    description = models.TextField()
    
    def __str__(self) -> str:
        return self.title

class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.CASCADE
    )

    def __str__(self):
        # выводим текст поста 
        return self.text 

yatube/posts/forms.py
from django import forms 
from .models import Post 

class PostForm(forms.ModelForm): 
    class Meta: 
        model = Post 
        labels = { 
            'group': 'группа', 
            'text': 'пост', 
        }
        fields = ('text', 'group') 

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect 
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
# Импортируем модель, чтобы обратиться к ней
from .models import Post, Group, User
from .forms import PostForm 
import datetime

# Create your views here.
SORTING = 10 

def year(request):
    """Добавляет переменную с текущим годом."""
    years = datetime.datetime.now()
    return years.year
years = year(year)

def index(request):
    post_list = Post.objects.all().order_by('-pub_date')
    # Если порядок сортировки определен в классе Meta модели,
    # запрос будет выглядеть так:
    # post_list = Post.objects.all()
    # Показывать по 10 записей на странице.
    paginator = Paginator(post_list, 10) 

    # Из URL извлекаем номер запрошенной страницы - это значение параметра page
    page_number = request.GET.get('page')

    # Получаем набор записей для страницы с запрошенным номером
    page_obj = paginator.get_page(page_number)
    # Отдаем в словаре контекста
    context = {
        'page_obj': page_obj,
        'years': years
        
    }
    return render(request, 'posts/index.html', context) 

# View-функция для страницы сообщества:


@login_required #декоратор для проверки залогиененых пользователей
def group_posts(request, slug):
    # Функция get_object_or_404 получает по заданным критериям объект 
    # из базы данных или возвращает сообщение об ошибке, если объект не найден.
    # В нашем случае в переменную group будут переданы объекты модели Group,
    # поле slug у которых соответствует значению slug в запросе
    group = get_object_or_404(Group, slug=slug)

    # Метод .filter позволяет ограничить поиск по критериям.
    # Это аналог добавления
    # условия WHERE group_id = {group_id}
    posts = Post.objects.filter(group=group).order_by('-pub_date')
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        #'posts': posts,
        'page_obj': page_obj,
        'years': years
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    # Здесь код запроса к модели и создание словаря контекста
    #author = get_object_or_404(Post, author=username)
    author = get_object_or_404(User, username=username) 
    posts = Post.objects.filter(author=author.id).order_by('-pub_date')
    #  page_obj = get_paginator(request, posts) 
    #posts = Post.objects.filter(author=username).order_by('-pub_date')
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'author': author,
        'posts': posts,
        'page_obj': page_obj,
        'years': years
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    author =  get_object_or_404(User, username=post.author)
    # Здесь код запроса к модели и создание словаря контекста
    context = {
        'post': post,
        'years': years,
        'author':author
    }
    return render(request, 'posts/post_detail.html', context)


@login_required 
def post_create(request): 
    form = PostForm(request.POST, files=request.FILES or None) 
    if request.method == 'POST': 

        if form.is_valid(): 
            post = form.save(commit=False) 
            post.author = request.user 
            post.save() 
            return redirect('posts:profile', request.user.username) 
    # form = PostForm() 
    template = 'posts/create_post.html' 
    context = { 
        'form': form,
        'years': years
    } 
    return render(request, template, context) 


@login_required
def post_edit(request, post_id): 
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(request.POST or None, instance=post)

    if request.user != post.author:
        return redirect('posts:post_detail', post_id)

    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)

    context = {
        'form': form,
        'is_edit': True,
        'post': post,
    }
    return render(request, 'posts/create_post.html', context)

yatube/templates/posts/create_post.html
{% extends "base.html" %} 
{% block title %} Новый пост 
{% endblock %} 
{% block content %}  
    <main> 
      <div class="container py-5"> 
        <div class="row justify-content-center"> 
          <div class="col-md-8 p-5"> 
            <div class="card"> 
              <div class="card-header">        
              {% if is_edit %}
                Редактировать пост 
              {% else %} 
                Новый пост 
              {% endif %}              
              </div> 
              <div class="card-body">         
                {% if is_edit %}         
                <form method="post" action="{% url 'posts:post_edit' post.id %}"> 
                {% csrf_token %} 
                {% else %} 
                <form method="post" action="{% url 'posts:post_create' %}"> 
                {% csrf_token %} 
                {% endif%}     
                  <div class="form-group row my-3 p-3"> 
                    <label for="id_text"> 
                      Текст поста               
                      <span class="required text-danger" >*</span>                   
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text"> 
                    </textarea>                 
                    <small id="id_text-help" class="form-text text-muted"> 
                      Текст нового поста
                    </small>                   
                  </div>             
                  <div class="form-group row my-3 p-3"> 
                    <label for="id_group"> 
                      Группа                   
                    </label> 
                    <select name="group" class="form-control" id="id_group"> 
                      {% for object in form.group %} 
                      <option value="{{ object.id }}"> {{ object }} </option> 
                      {% endfor%} 
                    </select> 
                    <small id="id_group-help" class="form-text text-muted"> 
                      Группа, к которой будет относиться пост 
                    </small> 
                  </div> 
                  <div class="d-flex justify-content-end"> 
                    <button type="submit" class="btn btn-primary"> 
                    {% if is_edit %} 
                      Сохранить 
                    {% else %} 
                      Добавить 
                    {% endif %}   
                    </button> 
                  </div> 
                </form> 
              </div> 
            </div> 
          </div> 
        </div> 
      </div> 
    </main> 
  </body> 
</html> 
{%endblock%} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
Записи сообщества:  {{ group.title }}
{% endblock %}
{% block content %} 
    <main>
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <div class="container">
          <h1>Записи сообщества {{ group.title }}</h1>
          <p>
            {{ group.description }}
          </p>
          
          {% for post in page_obj %}
            <ul>
              <li>
                Автор: <a href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            <p>{{ post.text|slice:300 }}<a href="{% url 'posts:post_detail' post.id %}"> ...</a></p>    
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %} 
          <!-- под последним постом нет линии -->
          
        </div>  
        {% include 'posts/includes/paginator.html' %} 
      </div> 
      
    </main>
    
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
Последние обновления на сайте
{% endblock %}
{% block content %} 
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">     
        <h1>Последние обновления на сайте</h1>
        {% for post in page_obj %}   
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            <p>{{ post.text |slice:"250" }} <a href="{% url 'posts:post_detail' post.id %}"> ...</a></p> 
            {% if post.group %}
                <a href="{% url 'posts:group_list' post.group.slug  %}">все записи группы</a>
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
        <!-- под последним постом нет линии -->
      </div>  
    
{% endblock %} 
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->      

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
{{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %} 
<main> 
  <div class="container py-5"> 
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:'d E Y' }}
            </li> 
            {% if post.group %}  
            <li class="list-group-item">
              Группа: {{ group.title }}
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
            </li>
            {% endif %} 
            <li class="list-group-item">
              Автор: {{post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  {{ author.posts.count }}
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
            {{ post.text|linebreaksbr }}
          </p>
          {% if user.id == post.author.id %}
             <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
             редактировать запись 
          </a>
          {% endif %} 
        </article>
      </div> 
    </div> 
  </main>
{% endblock %} 

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
Посты  {{ author.get_full_name }}
{% endblock %}
{% block content %} 
    <main>
      <div class="container py-5">        
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ author.posts.count }} </h3>   
        <article>
          <ul>
            <li>
              Автор: {{ author.get_full_name }}
            </li>
          </ul>
          <p>
            {% for post in page_obj %}   
            <p>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </p>
            <p>{{ post.text }}</p> 
            <p>
                <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>   
            </p>
            {% if post.group %}
                <a href="{% url 'posts:group_list' post.group.slug  %}">все записи группы</a>
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
          </p>
          
        </article>       
               
        <hr>
        <!-- Остальные посты. после последнего нет черты -->
        <!-- Здесь подключён паджинатор -->  
      </div>
    </main>
{% endblock %} 